function searchlights = OX_build_masked_searchlights( ...
        mask, affine, radius_mm, min_voxels)
%OX_BUILD_MASKED_SEARCHLIGHTS Build physical spheres restricted to a mask.

assert((islogical(mask) || isnumeric(mask)) && ndims(mask) == 3, ...
    'mask must be a three-dimensional array.');
assert(isnumeric(affine) && isequal(size(affine), [4, 4]) && ...
    all(isfinite(affine), 'all'), 'affine must be a finite 4-by-4 matrix.');
assert(isnumeric(radius_mm) && isscalar(radius_mm) && ...
    isfinite(radius_mm) && radius_mm > 0, ...
    'radius_mm must be a positive finite scalar.');
assert(isnumeric(min_voxels) && isscalar(min_voxels) && ...
    min_voxels >= 1 && min_voxels == round(min_voxels), ...
    'min_voxels must be a positive integer.');
mask = mask > 0;
feature_linear_indices = find(mask);
assert(~isempty(feature_linear_indices), 'The feature mask is empty.');
n_features = numel(feature_linear_indices);
feature_index_volume = zeros(size(mask), 'uint32');
feature_index_volume(feature_linear_indices) = uint32(1:n_features);
linear_part = affine(1:3, 1:3);
voxel_sizes = sqrt(sum(linear_part .^ 2, 1));
assert(all(isfinite(voxel_sizes)) && all(voxel_sizes > 0), ...
    'The affine has invalid voxel sizes.');

max_offset = ceil(radius_mm / min(voxel_sizes));
[dx, dy, dz] = ndgrid(-max_offset:max_offset, ...
    -max_offset:max_offset, -max_offset:max_offset);
offsets = [dx(:), dy(:), dz(:)];
world_offsets = linear_part * offsets';
distance = sqrt(sum(world_offsets .^ 2, 1));
offsets = offsets(distance <= radius_mm + 1e-8, :);
full_sphere_size = size(offsets, 1);

[center_x, center_y, center_z] = ind2sub(size(mask), ...
    feature_linear_indices);
all_neighborhoods = cell(n_features, 1);
all_sizes = zeros(n_features, 1);
for center_idx = 1:n_features
    coordinates = offsets + [center_x(center_idx), ...
        center_y(center_idx), center_z(center_idx)];
    in_bounds = coordinates(:, 1) >= 1 & ...
        coordinates(:, 1) <= size(mask, 1) & ...
        coordinates(:, 2) >= 1 & ...
        coordinates(:, 2) <= size(mask, 2) & ...
        coordinates(:, 3) >= 1 & ...
        coordinates(:, 3) <= size(mask, 3);
    coordinates = coordinates(in_bounds, :);
    linear_indices = sub2ind(size(mask), coordinates(:, 1), ...
        coordinates(:, 2), coordinates(:, 3));
    feature_indices = double(feature_index_volume(linear_indices));
    feature_indices = feature_indices(feature_indices > 0);
    all_neighborhoods{center_idx} = ...
        unique(feature_indices(:)', 'stable');
    all_sizes(center_idx) = numel(all_neighborhoods{center_idx});
end
assert(max(all_sizes) <= full_sphere_size, ...
    'A masked neighborhood exceeds the full sphere size.');
if abs(radius_mm - 4) < 1e-8 && all(abs(voxel_sizes - 2) < 1e-3)
    assert(full_sphere_size <= 33, ...
        ['A physical 4-mm sphere on this approximately 2-mm grid should ' ...
         'contain at most 33 voxels; found %d.'], ...
        full_sphere_size);
end

valid_centers = all_sizes >= min_voxels;
assert(any(valid_centers), ...
    'No center contains at least %d masked voxels.', min_voxels);
searchlights = struct( ...
    'feature_linear_indices', feature_linear_indices, ...
    'valid_center_membership', valid_centers, ...
    'center_linear_indices', feature_linear_indices(valid_centers), ...
    'neighborhoods', {all_neighborhoods(valid_centers)}, ...
    'neighborhood_sizes', all_sizes(valid_centers), ...
    'all_neighborhood_sizes', all_sizes, ...
    'full_sphere_size', full_sphere_size, ...
    'voxel_sizes_mm', voxel_sizes, ...
    'radius_mm', radius_mm, ...
    'minimum_voxels', min_voxels);
end
