function OX_rsa_write_readme(R)
fid=fopen(fullfile(R.output_dir,'README.md'),'w'); assert(fid>=0); cleanup=onCleanup(@() fclose(fid));
fprintf(fid,'# Formal %s RSA\n\n',R.analysis);
fprintf(fid,'Subjects 2–6; AON, PirF, PirT, olfAMG, olfOFC; PERSON, FOOD, LOCATION, CONTROL. Simple neural distance (1 - Pearson r), linear models without rank transformation. Physiology-regressed sniff estimates and saved RDMs are reused. See `results.mat` for input provenance, ROI voxel counts, condition order, and preprocessing.\n\n');
fprintf(fid,'## Models\n\n');
if R.analysis=="omnibus"
    fprintf(fid,'Omnibus figures display absolute standardized betas for each subject; saved coefficient estimates and inference retain their original signs.\n\n');
    fprintf(fid,'Boxchart stars use group-level BH-FDR q-values from the original signed-beta tests: * q < 0.05, ** q < 0.01, *** q < 0.001. No star means q >= 0.05. These are not tests of absolute beta magnitudes.\n\n');
    fprintf(fid,'Outcome: 3,160 upper-triangle neural distances per subject/ROI. Predictors: same odor, same context, pleasantness distance, intensity distance, with an intercept. All four predictors and the outcome use sample-SD z-scoring. Categorical predictors remain similarity-coded (1=same): negative beta indicates smaller distances for same-identity pairs after adjustment.\n\n');
else
    fprintf(fid,'Outcome: 120 same-odor cross-context distances per subject/ROI. Primary model: pleasantness change + intensity change + context-pair fixed effects + odor fixed effects. Sensitivity: omit odor fixed effects. Outcome and both rating changes are sample-SD z-scored; dummy variables are unscaled. The first context pair and odor 1 are references.\n\n');
end
fprintf(fid,'## Permutation inference\n\n');
fprintf(fid,['%d permutations per subject, using mt19937ar with seed = %d + subject_id * 100000. ' ...
    'Each permutation reorders both axes of the 80-condition neural RDM with one condition bijection. ' ...
    'The mapping is shared across ROIs and analyses, and independent across subjects. ' ...
    'Predictors remain fixed; neural outcomes are restandardized and the full model is refitted. ' ...
    'Displacement extracts nominal same-odor edges after relabeling. Individual entries are never shuffled independently.\n\n'], ...
    R.options.NumPermutations,R.options.PermutationSeed);
fprintf(fid,['This is a **global neural condition-correspondence null**, assuming exchangeability of neural condition identities under no association. ' ...
    'It is not a coefficient-specific conditional null, an exact trial-randomization test, or a within-run label shuffle. ' ...
    'It does not preserve the original odor/context correspondence in permuted neural distances.\n\n' ...
    'For every permutation, group null beta is the equal-weight average of the five subject null betas. ' ...
    'All five subjects are required. This is evidence for the measured five subjects, not a population random-effects claim; no group one-sample t-test is used.\n\n' ...
    'Two-sided p = min(1, 2 * min(1 + count(null <= observed), 1 + count(null >= observed)) / (B + 1)). ' ...
    'BH-FDR is applied across ROI × scientific predictor: 20 tests for omnibus, 10 per displacement model, separately within each subject and at group level. ' ...
    'Nuisance coefficients are saved without inferential claims. Null quantiles/dispersion are not confidence intervals for the observed effect.\n\n']);
if R.analysis=="displacement"
    fprintf(fid,'## Pooled mixed-effects scatterplots\n\n');
    fprintf(fid,['Separate univariate models for pleasantness and intensity in each ROI and focal semantic context (PERSON, FOOD, LOCATION). ' ...
        'Each pools the three pairs involving that context, including its CONTROL pair: 300 observations, five subjects, 60 observations per subject. ' ...
        'See `tables/mixed_model_context_membership.csv` for exact membership.\n\n' ...
        '```text\nneural_distance ~ context_pair + x + (1+x|subject) + (1|odor) + (1|subject_odor)\n```\n\n' ...
        'REML; subject intercept and slope covariance is diagonal. One common rating slope is tested per focal context, ROI, and rating; pair intercepts may differ. ' ...
        'Slope tests use two-sided Satterthwaite inference, 95%% pointwise confidence intervals, and BH-FDR across 30 slopes. ' ...
        'Semantic-context subsets overlap and are not independent cohorts. These tests assess association within each pooled subset, not a slope contrast against excluded pairs. ' ...
        'Standardized slopes equal raw slope * pooled SD(x)/SD(y), computed within ROI, rating, and focal-context subset. ' ...
        'Lines and bands are population fixed-effect predictions (random effects zero), equally averaging the three pair intercepts over the pooled observed x-range. ' ...
        'These models do not adjust for the other rating and use no permutation inference.\n\n' ...
        'Diagnostics include covariance components, near-zero variance flags, Hessian/fit warnings, residual tables, and residual plots. ' ...
        'Boundary thresholds: variance < max(1e-8, 1e-6 * residual variance). ' ...
        'Fits are not silently simplified. P-values and intervals remain model-based with only five subjects; the random-effects structure is a working covariance model for repeated observations.\n\n']);
    if isfield(R,'mixed_models')
        D=R.mixed_models.diagnostics;
        fprintf(fid,'Run diagnostics: %d of %d mixed models have a boundary variance flag; %d have fit warnings. See `tables/mixed_model_diagnostics.csv`.\n\n', ...
            nnz(D.boundary_variance),height(D),nnz(strlength(D.warning_message)>0));
    else
    fprintf(fid,'Mixed models were disabled for this run.\n\n');
    end
end
fprintf(fid,'## Files and verification\n\n');
fprintf(fid,['- `results.mat`: combined results, metadata, complete subject/group null arrays, and uint8 condition permutations.\n' ...
    '- `subject_results/`: observed coefficients, individual null arrays/statistics, seeds, mappings, and provenance.\n' ...
    '- `tables/`: subject/group statistics, group null CSVs, nuisance coefficients, fit/input QC, and condition ordering. Displacement also saves observations and mixed-model tables.\n' ...
    '- `figures/`: PNG and vector PDF outputs. Boxes summarize five subject betas; points identify subjects.\n' ...
    '- Null dimensions: subject × ROI × predictor × permutation; group arrays: ROI × predictor × permutation.\n\n' ...
    'Every observed scientific beta was checked against the exploratory simple/linear result (tolerance 1e-10). ' ...
    'Input condition mappings, finite outcomes, design ranks, permutation bijections, and exact five-subject null averaging are asserted. ' ...
    'Input warnings include missing ratings (subjects 2, 4, 6) and condition-count imbalance (subject 4); see input QC.\n\n']);
fprintf(fid,'Run options: MakePlots=%d, RunMixedModels=%d. Production uses 5000 permutations; smaller runs are smoke tests.\n',R.options.MakePlots,R.options.RunMixedModels);
end
