function inference = OX_searchlight_maxstat_inference(observed, null_stats)
%OX_SEARCHLIGHT_MAXSTAT_INFERENCE Joint studentized maximum inference.
%
% OBSERVED is centers-by-contexts and NULL_STATS is
% centers-by-contexts-by-permutations. Center-context statistics are
% standardized over the permutation-symmetric pool containing the observed
% labeling and every random labeling. Each null maximum is then taken over
% the complete center-by-context family.

assert(isnumeric(observed) && ismatrix(observed) && ...
    all(isfinite(observed), 'all'), ...
    'observed must be a finite numeric matrix.');
assert(isnumeric(null_stats) && ndims(null_stats) <= 3 && ...
    size(null_stats, 1) == size(observed, 1) && ...
    size(null_stats, 2) == size(observed, 2), ...
    'null_stats dimensions must match observed.');
n_permutations = size(null_stats, 3);
if n_permutations == 0
    inference = struct( ...
        'null_mean', nan(size(observed)), ...
        'null_sd', nan(size(observed)), ...
        'observed_z', nan(size(observed)), ...
        'p_uncorrected', nan(size(observed)), ...
        'p_fwe', nan(size(observed)), ...
        'significant_fwe05', false(size(observed)), ...
        'null_maximum_z', nan(0, 1));
    return;
end
assert(all(isfinite(null_stats), 'all'), ...
    'null_stats contains non-finite values.');

null_double = double(null_stats);
pool_mean = (observed + sum(null_double, 3)) / (n_permutations + 1);
pool_sum_squares = (observed - pool_mean) .^ 2 + ...
    sum((null_double - pool_mean) .^ 2, 3);
pool_sd = sqrt(pool_sum_squares / n_permutations);
assert(all(isfinite(pool_sd), 'all') && all(pool_sd > eps, 'all'), ...
    'A center-context test has zero or invalid permutation variance.');
observed_z = (observed - pool_mean) ./ pool_sd;

null_maximum_z = nan(n_permutations, 1);
batch_size = 250;
for batch_start = 1:batch_size:n_permutations
    indices = batch_start:min(batch_start + batch_size - 1, n_permutations);
    z_batch = (null_double(:, :, indices) - pool_mean) ./ pool_sd;
    null_maximum_z(indices) = max(reshape( ...
        z_batch, [], numel(indices)), [], 1)';
end
p_uncorrected = (1 + sum(null_double >= observed, 3)) / ...
    (n_permutations + 1);
p_fwe = nan(size(observed));
for center_idx = 1:size(observed, 1)
    for context_idx = 1:size(observed, 2)
        p_fwe(center_idx, context_idx) = ...
            (1 + sum(null_maximum_z >= observed_z(center_idx, context_idx))) / ...
            (n_permutations + 1);
    end
end

inference = struct( ...
    'null_mean', pool_mean, ...
    'null_sd', pool_sd, ...
    'observed_z', observed_z, ...
    'p_uncorrected', p_uncorrected, ...
    'p_fwe', p_fwe, ...
    'significant_fwe05', p_fwe <= 0.05, ...
    'null_maximum_z', null_maximum_z);
end
