function results = OX_searchlight_context_split_half_similarity( ...
        subjidx, varargin)
%OX_SEARCHLIGHT_CONTEXT_SPLIT_HALF_SIMILARITY Restricted context searchlight.
%
%   RESULTS = OX_SEARCHLIGHT_CONTEXT_SPLIT_HALF_SIMILARITY(SUBJIDX, ...)
%
% The analysis uses physio-regressed odor-aligned GLMsingle estimates and
% restricts centers and features to the union of bilateral TU, AON, PirF,
% PirT, olfAMG, EC, and HIPP, intersected with gray matter and the fixed
% uncorrected Odor > Rest p<.001 mask. Three context-specific cross-half
% similarity maps are corrected together with a participant-level
% studentized maximum statistic.

p = inputParser;
p.FunctionName = mfilename;
addRequired(p, 'subjidx', @(x) isnumeric(x) && isscalar(x) && ...
    isfinite(x) && x == round(x));
addParameter(p, 'MRIRoot', '', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'CueRoot', '', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'NumSplits', 200, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && x == round(x));
addParameter(p, 'MaxSplitAttempts', 100000, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && x == round(x));
addParameter(p, 'RandomSeed', 1, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'SearchlightRadiusMM', 4, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x > 0);
addParameter(p, 'MinVoxels', 10, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 2 && x == round(x));
addParameter(p, 'NumPermutations', 5000, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0 && x == round(x));
addParameter(p, 'PermutationSeed', 1001, ...
    @(x) isnumeric(x) && isscalar(x) && isfinite(x) && x >= 0);
addParameter(p, 'PermutationBatchSize', 25, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && x == round(x));
addParameter(p, 'MaxPermutationLabelAttempts', 1000, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && x == round(x));
addParameter(p, 'UseParallel', true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p, 'Resume', true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p, 'KeepCheckpoint', true, ...
    @(x) islogical(x) && isscalar(x));
addParameter(p, 'OutputDir', '', ...
    @(x) ischar(x) || (isstring(x) && isscalar(x)));
addParameter(p, 'SaveOutputs', true, ...
    @(x) islogical(x) && isscalar(x));
parse(p, subjidx, varargin{:});
opts = p.Results;

subject_real_names = {'240711_fMRI_OX_NWU_AS', ...
                      '240723_fMRI_OX_NWU_LS', ...
                      '240814_fMRI_OX_NWU_JN', ...
                      '240816_fMRI_OX_NWU_RR', ...
                      '241018_fMRI_OX_NWU_BN', ...
                      '250117_fMRI_OX_NWU_VS'};
assert(subjidx >= 1 && subjidx <= numel(subject_real_names), ...
    'subjidx must be between 1 and %d.', numel(subject_real_names));
assert(exist('spm_vol', 'file') == 2 && exist('spm_read_vols', 'file') == 2, ...
    'SPM must be on the MATLAB path. Run setup_ox first.');

analysis_tic = tic;
subject_name = sprintf('subj_%d', subjidx);
mri_root = resolve_mri_root(opts.MRIRoot);
nifti_dir = fullfile(mri_root, subject_name, 'nifti');
beta_dir = fullfile(nifti_dir, 'sniff_single_trial_by_category_physio');
fit_file = fullfile(beta_dir, 'TYPED_FITHRF_GLMDENOISE_RR.mat');
gm_mask_file = fullfile(nifti_dir, 'coreg', 'gm_mask_thr05_func.nii');
functional_mask_file = fullfile(nifti_dir, ...
    'first_level_model_sniff_physio', ...
    'spmT_0001_uncorrected_p001.nii');
if strlength(string(opts.OutputDir)) == 0
    output_dir = fullfile(nifti_dir, ...
        'olf_context_similarity_searchlight');
else
    output_dir = char(string(opts.OutputDir));
end
assert(isfile(fit_file), 'Missing GLMsingle file: %s', fit_file);
assert(isfile(gm_mask_file), 'Missing gray-matter mask: %s', gm_mask_file);
assert(isfile(functional_mask_file), ...
    'Missing functional restriction mask: %s', functional_mask_file);
if opts.SaveOutputs && ~isfolder(output_dir)
    mkdir(output_dir);
end

fprintf('\n[OLF CONTEXT SIMILARITY SEARCHLIGHT] %s\n', subject_name);
fprintf('Loading %s\n', fit_file);
loaded = load(fit_file, 'modelmd');
assert(isfield(loaded, 'modelmd'), 'GLMsingle file lacks modelmd.');
modelmd = squeeze(loaded.modelmd);
clear loaded
assert(ismatrix(modelmd), 'squeeze(modelmd) must be two-dimensional.');

metadata_args = {};
if strlength(string(opts.CueRoot)) > 0
    metadata_args = {'CueRoot', char(string(opts.CueRoot))};
end
all_metadata = OX_load_trial_metadata(subjidx, metadata_args{:});
assert(size(modelmd, 2) == height(all_metadata), ...
    'modelmd has %d trials but metadata has %d.', ...
    size(modelmd, 2), height(all_metadata));
context_order = ["PERSON", "FOOD", "LOCATION"];
semantic_mask = ismember(all_metadata.context, context_order);
assert(nnz(semantic_mask) == 600, ...
    'Expected 600 semantic trials; found %d.', nnz(semantic_mask));
trial_metadata = all_metadata(semantic_mask, :);
modelmd = modelmd(:, semantic_mask);
modelmd = center_voxels_within_runs(modelmd, trial_metadata.run_id);

gm_header = spm_vol(gm_mask_file);
gm_mask = spm_read_vols(gm_header) > 0;
gm_indices = find(gm_mask);
assert(size(modelmd, 1) == numel(gm_indices), ...
    ['Mapping check failed: modelmd has %d rows but find(gm_mask) has ' ...
     '%d voxels.'], size(modelmd, 1), numel(gm_indices));
functional_header = spm_vol(functional_mask_file);
assert_same_geometry(functional_header, gm_header, ...
    functional_mask_file, gm_mask_file);
functional_mask = spm_read_vols(functional_header) > 0;

[roi_union, roi_metadata] = load_roi_union(nifti_dir, gm_header);
finite_model_rows = all(isfinite(modelmd), 2);
finite_volume = false(size(gm_mask));
finite_volume(gm_indices) = finite_model_rows;
final_mask = roi_union & gm_mask & functional_mask & finite_volume;
assert(any(final_mask(:)), 'The final restriction mask is empty.');

model_index_volume = zeros(size(gm_mask), 'uint32');
model_index_volume(gm_indices) = uint32(1:numel(gm_indices));
feature_linear_indices = find(final_mask);
feature_model_indices = double(model_index_volume(feature_linear_indices));
assert(all(feature_model_indices > 0), ...
    'A final-mask voxel has no GLMsingle row mapping.');
X = double(modelmd(feature_model_indices, :)');
assert(all(isfinite(X), 'all'), ...
    'Restricted semantic-trial feature matrix contains non-finite values.');

searchlight_definition = OX_build_masked_searchlights(final_mask, ...
    gm_header.mat, opts.SearchlightRadiusMM, opts.MinVoxels);
assert(isequal(searchlight_definition.feature_linear_indices, ...
    feature_linear_indices), ...
    'Searchlight feature order differs from the GLMsingle feature order.');
valid_centers = searchlight_definition.valid_center_membership;
neighborhoods = searchlight_definition.neighborhoods;
neighborhood_sizes = searchlight_definition.neighborhood_sizes;
center_linear_indices = searchlight_definition.center_linear_indices;
full_sphere_size = searchlight_definition.full_sphere_size;
n_centers = numel(center_linear_indices);

fprintf(['Semantic trials: %d | runs: %d | final features: %d | ' ...
    'valid centers: %d\n'], height(trial_metadata), ...
    numel(unique(trial_metadata.run_id)), numel(feature_linear_indices), ...
    n_centers);
fprintf(['Radius: %.3g mm | full sphere: %d voxels | neighborhood ' ...
    'range: %d-%d | median: %.0f\n'], opts.SearchlightRadiusMM, ...
    full_sphere_size, min(neighborhood_sizes), max(neighborhood_sizes), ...
    median(neighborhood_sizes));

fprintf('Scoring observed labeling with %d session-balanced splits...\n', ...
    opts.NumSplits);
observed = OX_searchlight_context_split_half_score(X, ...
    trial_metadata.odor, trial_metadata.context, trial_metadata.run_id, ...
    trial_metadata.session_id, neighborhoods, ...
    'NumSplits', opts.NumSplits, ...
    'RandomSeed', opts.RandomSeed, ...
    'MaxSplitAttempts', opts.MaxSplitAttempts, ...
    'ExpectedOdors', 20, ...
    'CollectSplitDetails', true);
observed_context_delta_z = observed.context_mean_delta_z;
assert(all(isfinite(observed_context_delta_z), 'all'), ...
    'Observed searchlight map contains a non-finite statistic.');

[null_context_delta_z, permutation_metadata, checkpoint_file] = ...
    run_permutations(X, trial_metadata, neighborhoods, ...
    center_linear_indices, neighborhood_sizes, opts, subjidx, output_dir);

inference = OX_searchlight_maxstat_inference( ...
    observed_context_delta_z, null_context_delta_z);

results = struct();
results.subject = struct('index', subjidx, 'name', subject_name, ...
    'name_real', subject_real_names{subjidx});
results.analysis = struct( ...
    'name', 'restricted_context_split_half_similarity_searchlight', ...
    'context_order', {cellstr(context_order(:))}, ...
    'context_statistic', ['Fisher-z same-context cross-half similarity ' ...
        'minus the mean of four bidirectional different-context cells'], ...
    'split_unit', 'acquisition run', ...
    'template_weighting', ['within context and half: mean repetitions ' ...
        'within odor, then equal mean across 20 odors'], ...
    'inference_level', 'participant', ...
    'multiple_testing_family', ...
        'all valid searchlight centers times three contexts', ...
    'fwe_method', 'studentized single-step permutation maximum statistic');
results.preprocessing = struct( ...
    'semantic_trials_only', true, ...
    'control_trials_used', false, ...
    'within_run_voxel_centering', true, ...
    'scale_voxels', false, ...
    'whiten_voxels', false, ...
    'spatial_similarity', 'Pearson correlation', ...
    'gray_matter_mask', gm_mask_file, ...
    'functional_restriction', functional_mask_file);
results.inputs = struct('fit_file', fit_file, ...
    'roi_metadata', roi_metadata);
results.trial_metadata = trial_metadata;
results.mask = struct( ...
    'n_roi_union_voxels', nnz(roi_union), ...
    'n_gray_matter_voxels', nnz(gm_mask), ...
    'n_functional_voxels', nnz(functional_mask), ...
    'n_final_features', numel(feature_linear_indices), ...
    'n_valid_centers', n_centers, ...
    'feature_linear_indices', feature_linear_indices, ...
    'feature_model_indices', feature_model_indices, ...
    'center_linear_indices', center_linear_indices);
results.searchlight = struct( ...
    'radius_mm', opts.SearchlightRadiusMM, ...
    'full_sphere_voxels', full_sphere_size, ...
    'minimum_voxels', opts.MinVoxels, ...
    'neighborhood_sizes', neighborhood_sizes, ...
    'neighborhoods', {neighborhoods}, ...
    'centers_and_features_restricted_to_final_mask', true);
results.observed = struct( ...
    'context_delta_z', observed_context_delta_z, ...
    'null_standardized_z', inference.observed_z, ...
    'split_details', observed);
results.null = struct( ...
    'context_delta_z', null_context_delta_z, ...
    'center_context_mean', inference.null_mean, ...
    'center_context_sd', inference.null_sd, ...
    'maximum_z', inference.null_maximum_z, ...
    'metadata', permutation_metadata, ...
    'exchangeability', ['semantic context labels shuffled within exact ' ...
        'acquisition run; run context counts, odors, data, and masks fixed'], ...
    'standardization_pool', 'observed labeling plus all permutations');
results.inference = struct( ...
    'p_uncorrected', inference.p_uncorrected, ...
    'p_fwe', inference.p_fwe, ...
    'significant_fwe05', inference.significant_fwe05, ...
    'empirical_p_formula', '(1 + exceedances) / (NumPermutations + 1)', ...
    'joint_context_correction', true);
results.options = opts;
results.output_dir = output_dir;
results.checkpoint_file = checkpoint_file;
results.runtime_minutes = toc(analysis_tic) / 60;
results.matlab_version = version;

if opts.SaveOutputs
    write_outputs(results, gm_header, size(gm_mask), roi_union, final_mask, ...
        valid_centers, feature_linear_indices, output_dir);
    if ~opts.KeepCheckpoint && isfile(checkpoint_file)
        delete(checkpoint_file);
        results.checkpoint_file = '';
    end
    results_file = fullfile(output_dir, sprintf( ...
        'olf_context_similarity_searchlight_subj%d_results.mat', subjidx));
    save(results_file, 'results', '-v7.3');
    fprintf('Saved full results to %s\n', results_file);
end
fprintf('Completed %s in %.1f minutes.\n', subject_name, ...
    toc(analysis_tic) / 60);
end

function [roi_union, metadata] = load_roi_union(nifti_dir, reference_header)
roi_root = fullfile(nifti_dir, 'coreg', 'roi_decoding');
names = ["TU"; "AON"; "PirF"; "PirT"; "olfAMG"; "EC"; "HIPP"];
groups = ["secondary"; "primary"; "primary"; "primary"; ...
          "primary"; "primary"; "primary"];
basenames = ["olf_TU_bilateral_func_thr02.nii"; ...
             "AON_bilateral_func_thr02.nii"; ...
             "PirF_bilateral_func_thr02.nii"; ...
             "PirT_bilateral_func_thr02.nii"; ...
             "olfAMG_bilateral_func_thr02.nii"; ...
             "EC_bilateral_func_thr02.nii"; ...
             "HIPP_bilateral_func_thr02.nii"];
roi_union = false(reference_header.dim);
n_mask_voxels = zeros(numel(names), 1);
files = strings(numel(names), 1);
for roi_idx = 1:numel(names)
    files(roi_idx) = fullfile(roi_root, groups(roi_idx), basenames(roi_idx));
    assert(isfile(files(roi_idx)), 'Missing ROI mask: %s', files(roi_idx));
    header = spm_vol(char(files(roi_idx)));
    assert_same_geometry(header, reference_header, files(roi_idx), ...
        reference_header.fname);
    mask = spm_read_vols(header) > 0;
    n_mask_voxels(roi_idx) = nnz(mask);
    roi_union = roi_union | mask;
end
metadata = table(names, groups, basenames, files, n_mask_voxels, ...
    'VariableNames', {'roi', 'selection_group', 'basename', 'file', ...
    'n_mask_voxels'});
end

function [null_stats, metadata, checkpoint_file] = run_permutations( ...
        X, trial_metadata, neighborhoods, center_linear_indices, ...
        neighborhood_sizes, opts, subjidx, output_dir)
n_permutations = opts.NumPermutations;
n_centers = numel(neighborhoods);
checkpoint_file = '';
metadata = initialize_permutation_metadata(n_permutations, opts, subjidx);
if n_permutations == 0
    null_stats = nan(n_centers, 3, 0, 'single');
    metadata.runtime_minutes = 0;
    return;
end

use_checkpoint = opts.SaveOutputs;
configuration = checkpoint_configuration(subjidx, center_linear_indices, ...
    neighborhood_sizes, neighborhoods, X, opts);
if use_checkpoint
    if ~isfolder(output_dir)
        mkdir(output_dir);
    end
    checkpoint_file = fullfile(output_dir, sprintf( ...
        'olf_context_similarity_searchlight_subj%d_checkpoint.mat', subjidx));
end

if use_checkpoint && opts.Resume && isfile(checkpoint_file)
    saved = load(checkpoint_file, 'configuration', ...
        'permutation_completed', 'context_seed_used', ...
        'label_attempts', 'split_attempts', 'split_coverage_rejections', ...
        'split_duplicate_rejections');
    assert(isfield(saved, 'configuration') && ...
        isequaln(saved.configuration, configuration), ...
        ['Checkpoint configuration does not match this analysis. Use a ' ...
         'different OutputDir or remove the stale checkpoint.']);
    permutation_completed = saved.permutation_completed;
    metadata.context_seed_used = saved.context_seed_used;
    metadata.label_attempts = saved.label_attempts;
    metadata.split_attempts = saved.split_attempts;
    metadata.split_coverage_rejections = saved.split_coverage_rejections;
    metadata.split_duplicate_rejections = saved.split_duplicate_rejections;
    checkpoint = matfile(checkpoint_file, 'Writable', true);
    fprintf('Resuming checkpoint with %d/%d permutations complete.\n', ...
        nnz(permutation_completed), n_permutations);
else
    permutation_completed = false(1, n_permutations);
    null_stats = nan(n_centers, 3, n_permutations, 'single');
    context_seed_used = metadata.context_seed_used;
    label_attempts = metadata.label_attempts;
    split_attempts = metadata.split_attempts;
    split_coverage_rejections = metadata.split_coverage_rejections;
    split_duplicate_rejections = metadata.split_duplicate_rejections;
    if use_checkpoint
        null_context_delta_z = null_stats;
        save(checkpoint_file, 'configuration', 'null_context_delta_z', ...
            'permutation_completed', 'context_seed_used', ...
            'label_attempts', 'split_attempts', ...
            'split_coverage_rejections', 'split_duplicate_rejections', ...
            '-v7.3');
        checkpoint = matfile(checkpoint_file, 'Writable', true);
    end
end

use_parallel = opts.UseParallel && license('test', ...
    'Distrib_Computing_Toolbox');
if opts.UseParallel && ~use_parallel
    warning('Parallel Computing Toolbox unavailable; permutations are serial.');
end
if use_parallel && isempty(gcp('nocreate'))
    parpool;
end

remaining = find(~permutation_completed);
fprintf('Running %d remaining within-run context permutations...\n', ...
    numel(remaining));
permutation_tic = tic;
batch_size = min(opts.PermutationBatchSize, max(1, numel(remaining)));
for batch_start = 1:batch_size:numel(remaining)
    batch_indices = remaining(batch_start:min( ...
        batch_start + batch_size - 1, numel(remaining)));
    batch_results = cell(numel(batch_indices), 1);
    if use_parallel
        parfor batch_position = 1:numel(batch_indices)
            permutation_idx = batch_indices(batch_position);
            batch_results{batch_position} = evaluate_permutation( ...
                X, trial_metadata, neighborhoods, opts, subjidx, ...
                permutation_idx);
        end
    else
        for batch_position = 1:numel(batch_indices)
            permutation_idx = batch_indices(batch_position);
            batch_results{batch_position} = evaluate_permutation( ...
                X, trial_metadata, neighborhoods, opts, subjidx, ...
                permutation_idx);
        end
    end
    batch_stats = nan(n_centers, 3, numel(batch_indices), 'single');
    for batch_position = 1:numel(batch_indices)
        permutation_idx = batch_indices(batch_position);
        item = batch_results{batch_position};
        batch_stats(:, :, batch_position) = ...
            single(item.context_mean_delta_z);
        metadata.context_seed_used(permutation_idx) = item.context_seed_used;
        metadata.label_attempts(permutation_idx) = item.label_attempts;
        metadata.split_attempts(permutation_idx) = item.split_attempts;
        metadata.split_coverage_rejections(permutation_idx) = ...
            item.split_coverage_rejections;
        metadata.split_duplicate_rejections(permutation_idx) = ...
            item.split_duplicate_rejections;
    end
    if use_checkpoint
        checkpoint.null_context_delta_z(:, :, batch_indices) = batch_stats;
        checkpoint.context_seed_used(1, batch_indices) = ...
            metadata.context_seed_used(batch_indices);
        checkpoint.label_attempts(1, batch_indices) = ...
            metadata.label_attempts(batch_indices);
        checkpoint.split_attempts(1, batch_indices) = ...
            metadata.split_attempts(batch_indices);
        checkpoint.split_coverage_rejections(1, batch_indices) = ...
            metadata.split_coverage_rejections(batch_indices);
        checkpoint.split_duplicate_rejections(1, batch_indices) = ...
            metadata.split_duplicate_rejections(batch_indices);
        permutation_completed(batch_indices) = true;
        checkpoint.permutation_completed = permutation_completed;
    else
        null_stats(:, :, batch_indices) = batch_stats;
        permutation_completed(batch_indices) = true;
    end
    fprintf('  permutations %d/%d complete | %.1f min this run\n', ...
        nnz(permutation_completed), n_permutations, toc(permutation_tic) / 60);
end
assert(all(permutation_completed), ...
    'Permutation run ended with incomplete checkpoint entries.');
if use_checkpoint
    null_stats = checkpoint.null_context_delta_z;
end
assert(all(isfinite(null_stats), 'all'), ...
    'Permutation statistic cube contains non-finite values.');
metadata.completed = permutation_completed;
metadata.runtime_minutes = toc(permutation_tic) / 60;
end

function configuration = checkpoint_configuration(subjidx, centers, ...
        sizes, neighborhoods, X, opts)
configuration = struct( ...
    'version', 1, ...
    'subject', subjidx, ...
    'center_linear_indices', centers, ...
    'neighborhood_sizes', sizes, ...
    'neighborhoods', {neighborhoods}, ...
    'data_size', size(X), ...
    'data_sum', sum(X, 'all'), ...
    'data_sum_squares', sum(X .^ 2, 'all'), ...
    'num_splits', opts.NumSplits, ...
    'max_split_attempts', opts.MaxSplitAttempts, ...
    'split_seed', opts.RandomSeed, ...
    'radius_mm', opts.SearchlightRadiusMM, ...
    'minimum_voxels', opts.MinVoxels, ...
    'num_permutations', opts.NumPermutations, ...
    'permutation_seed', opts.PermutationSeed, ...
    'max_label_attempts', opts.MaxPermutationLabelAttempts);
end

function metadata = initialize_permutation_metadata(n_permutations, opts, ...
        subjidx)
metadata = struct();
metadata.n_permutations = n_permutations;
metadata.context_seed_initial = opts.PermutationSeed + ...
    subjidx * 100000 + (1:n_permutations);
metadata.context_seed_used = nan(1, n_permutations);
metadata.label_attempts = zeros(1, n_permutations, 'uint16');
metadata.split_attempts = zeros(1, n_permutations, 'uint32');
metadata.split_coverage_rejections = zeros(1, n_permutations, 'uint32');
metadata.split_duplicate_rejections = zeros(1, n_permutations, 'uint32');
metadata.split_sampling_seed = opts.RandomSeed;
metadata.label_resampling = ['draw another within-run permutation only ' ...
    'when the labeling cannot furnish the requested number of valid splits'];
end

function item = evaluate_permutation(X, trial_metadata, neighborhoods, ...
        opts, subjidx, permutation_idx)
initial_seed = opts.PermutationSeed + subjidx * 100000 + permutation_idx;
for label_attempt = 1:opts.MaxPermutationLabelAttempts
    seed_used = initial_seed + (label_attempt - 1) * 10000000;
    permuted_contexts = OX_permute_semantic_context_within_runs( ...
        trial_metadata.context, trial_metadata.run_id, seed_used);
    try
        score = OX_searchlight_context_split_half_score(X, ...
            trial_metadata.odor, permuted_contexts, ...
            trial_metadata.run_id, trial_metadata.session_id, ...
            neighborhoods, 'NumSplits', opts.NumSplits, ...
            'RandomSeed', opts.RandomSeed, ...
            'MaxSplitAttempts', opts.MaxSplitAttempts, ...
            'ExpectedOdors', 20, 'CollectSplitDetails', false);
        item = struct( ...
            'context_mean_delta_z', score.context_mean_delta_z, ...
            'context_seed_used', seed_used, ...
            'label_attempts', label_attempt, ...
            'split_attempts', score.n_attempted_splits, ...
            'split_coverage_rejections', score.n_rejected_coverage, ...
            'split_duplicate_rejections', score.n_rejected_duplicate);
        return;
    catch exception
        resample_identifiers = { ...
            'OX_DATA:IncompleteContextOdorCoverage', ...
            'OX_DATA:InsufficientValidSplits'};
        if ~ismember(exception.identifier, resample_identifiers)
            rethrow(exception);
        end
        % This labeling is not estimable. Draw a new within-run context
        % permutation; the imaging trials themselves remain fixed.
    end
end
error('OX_DATA:NoEligibleContextPermutation', ...
    ['Unable to generate a split-eligible context permutation in %d ' ...
     'attempts for permutation %d.'], ...
    opts.MaxPermutationLabelAttempts, permutation_idx);
end

function write_outputs(results, reference_header, volume_size, roi_union, ...
        final_mask, valid_centers, feature_linear_indices, output_dir)
subjidx = results.subject.index;
prefix = sprintf('olf_context_similarity_subj%d', subjidx);
write_binary_volume(reference_header, roi_union, ...
    fullfile(output_dir, [prefix '_roi_union.nii']));
write_binary_volume(reference_header, final_mask, ...
    fullfile(output_dir, [prefix '_final_restriction_mask.nii']));
center_support = false(volume_size);
center_support(results.mask.center_linear_indices) = true;
write_binary_volume(reference_header, center_support, ...
    fullfile(output_dir, [prefix '_valid_center_mask.nii']));
all_sizes = nan(volume_size);
all_sizes(feature_linear_indices(valid_centers)) = ...
    results.searchlight.neighborhood_sizes;
write_float_volume(reference_header, all_sizes, ...
    fullfile(output_dir, [prefix '_neighborhood_size.nii']));

contexts = lower(string(results.analysis.context_order));
for context_idx = 1:3
    context_name = char(contexts(context_idx));
    base = sprintf('%s_%s', prefix, context_name);
    write_center_map(reference_header, volume_size, ...
        results.mask.center_linear_indices, ...
        results.observed.context_delta_z(:, context_idx), ...
        fullfile(output_dir, [base '_delta_z.nii']));
    write_center_map(reference_header, volume_size, ...
        results.mask.center_linear_indices, ...
        results.observed.null_standardized_z(:, context_idx), ...
        fullfile(output_dir, [base '_null_z.nii']));
    write_center_map(reference_header, volume_size, ...
        results.mask.center_linear_indices, ...
        results.inference.p_uncorrected(:, context_idx), ...
        fullfile(output_dir, [base '_p_uncorrected.nii']));
    write_center_map(reference_header, volume_size, ...
        results.mask.center_linear_indices, ...
        results.inference.p_fwe(:, context_idx), ...
        fullfile(output_dir, [base '_p_fwe_maxstat.nii']));
    significant_map = false(volume_size);
    significant_map(results.mask.center_linear_indices) = ...
        results.inference.significant_fwe05(:, context_idx);
    write_binary_volume(reference_header, significant_map, ...
        fullfile(output_dir, [base '_sig_fwe_p05.nii']));
end
end

function write_center_map(header, volume_size, linear_indices, values, file)
volume = nan(volume_size);
volume(linear_indices) = values;
write_float_volume(header, volume, file);
end

function write_float_volume(reference_header, volume, file)
header = reference_header;
header.fname = file;
header.dt = [16, 0];
header.pinfo = [1; 0; 0];
spm_write_vol(header, single(volume));
end

function write_binary_volume(reference_header, volume, file)
header = reference_header;
header.fname = file;
header.dt = [2, 0];
header.pinfo = [1; 0; 0];
spm_write_vol(header, uint8(volume > 0));
end

function modelmd = center_voxels_within_runs(modelmd, run_ids)
runs = unique(run_ids, 'stable');
for run_idx = 1:numel(runs)
    in_run = run_ids == runs(run_idx);
    modelmd(:, in_run) = modelmd(:, in_run) - ...
        mean(modelmd(:, in_run), 2);
end
end

function assert_same_geometry(image_header, reference_header, ...
        image_file, reference_file)
assert(isequal(image_header.dim, reference_header.dim), ...
    'Dimension mismatch between %s and %s.', image_file, reference_file);
assert(max(abs(image_header.mat(:) - reference_header.mat(:))) < 1e-4, ...
    'Affine mismatch between %s and %s.', image_file, reference_file);
end

function mri_root = resolve_mri_root(requested)
if strlength(string(requested)) > 0
    mri_root = char(string(requested));
    assert(isfolder(mri_root), 'MRIRoot does not exist: %s', mri_root);
    return;
end
candidates = {'/Users/qhyang/Desktop/OX_DATA/MRI', ...
              '/Volumes/ExtremeSSD/OX_DATA/MRI'};
mri_root = '';
for candidate_idx = 1:numel(candidates)
    if isfolder(candidates{candidate_idx})
        mri_root = candidates{candidate_idx};
        break;
    end
end
assert(~isempty(mri_root), ...
    'Could not auto-detect MRIRoot. Pass it with ''MRIRoot''.');
end
