function test_results = OX_test_context_split_half_similarity()
%OX_TEST_CONTEXT_SPLIT_HALF_SIMILARITY Synthetic sanity checks.
%
% Stable context-specific spatial patterns plus independent noise must
% produce positive diagonal-minus-off-diagonal Fisher-z similarity. Pure
% independent noise should average to approximately zero.

previous_rng = rng;
cleanup = onCleanup(@() rng(previous_rng));
rng(271828, 'twister');

n_runs = 20;
n_odors = 20;
n_contexts = 3;
n_voxels = 300;
n_trials = n_runs * n_odors * n_contexts;
run_ids = repelem((1:n_runs)', n_odors * n_contexts);
odor_labels = repmat(repelem((1:n_odors)', n_contexts), n_runs, 1);
context_index = repmat(repmat((1:n_contexts)', n_odors, 1), n_runs, 1);
context_names = ["PERSON", "FOOD", "LOCATION"];
context_labels = context_names(context_index)';
context_labels = context_labels(:);
session_ids = repelem((1:4)', 5 * n_odors * n_contexts);
assert(numel(run_ids) == n_trials && numel(session_ids) == n_trials, ...
    'Synthetic metadata construction failed.');

% Orthogonal, spatially demeaned context signals give a clear positive
% control without imposing voxel scaling in the analysis itself.
[basis, ~] = qr(randn(n_voxels, n_contexts), 0);
context_patterns = (4 * basis)';
context_patterns = context_patterns - mean(context_patterns, 2);
stable_X = context_patterns(context_index, :) + 0.7 * randn(n_trials, n_voxels);
noise_X = randn(n_trials, n_voxels);

common_args = {'NumSplits', 100, 'RandomSeed', 17, ...
    'StratifyGroups', session_ids, 'ExpectedOdors', n_odors, ...
    'MaxSplitAttempts', 20000};
stable = OX_context_split_half_similarity(stable_X, odor_labels, ...
    context_labels, run_ids, common_args{:});
noise = OX_context_split_half_similarity(noise_X, odor_labels, ...
    context_labels, run_ids, common_args{:});

n_null = 20;
null_max_delta_z = nan(1, n_null);
for permutation_idx = 1:n_null
    permuted_contexts = OX_permute_semantic_context_within_runs( ...
        context_labels, run_ids, 5000 + permutation_idx);
    permuted = OX_context_split_half_similarity(stable_X, odor_labels, ...
        permuted_contexts, run_ids, 'NumSplits', 30, ...
        'RandomSeed', 7000 + permutation_idx, ...
        'StratifyGroups', session_ids, 'ExpectedOdors', n_odors, ...
        'MaxSplitAttempts', 20000, 'CollectDetails', false);
    null_max_delta_z(permutation_idx) = permuted.aggregate.max_delta_z;
end

assert(stable.aggregate.mean_delta_z > 0.5, ...
    'Stable context patterns did not produce a clear positive delta-z (%.4f).', ...
    stable.aggregate.mean_delta_z);
assert(abs(noise.aggregate.mean_delta_z) < 0.15, ...
    'Pure noise delta-z was not approximately zero (%.4f).', ...
    noise.aggregate.mean_delta_z);
assert(isequal(size(stable.raw_r), [3, 3, 100]) && ...
    isequal(size(stable.fisher_z), [3, 3, 100]), ...
    'Split-level similarity matrices have unexpected dimensions.');
assert(all(stable.cell_trial_counts(:) > 0) && ...
    all(noise.cell_trial_counts(:) > 0), ...
    'A retained synthetic split contains an empty context-by-odor cell.');
assert(abs(mean(stable.aggregate.mean_context_delta_z) - ...
        stable.aggregate.mean_delta_z) < 1e-10, ...
    'Context-specific effects do not reconstruct the overall effect.');
assert(stable.aggregate.max_delta_z > max(null_max_delta_z), ...
    ['Stable context patterns did not exceed the synthetic within-run ' ...
     'permutation max-delta null.']);

test_results = struct( ...
    'stable_mean_delta_z', stable.aggregate.mean_delta_z, ...
    'noise_mean_delta_z', noise.aggregate.mean_delta_z, ...
    'stable_max_delta_z', stable.aggregate.max_delta_z, ...
    'permutation_max_delta_z', null_max_delta_z, ...
    'stable_pass', stable.aggregate.mean_delta_z > 0.5, ...
    'noise_pass', abs(noise.aggregate.mean_delta_z) < 0.15, ...
    'permutation_pass', stable.aggregate.max_delta_z > max(null_max_delta_z));
fprintf(['Context split-half synthetic test passed | stable delta-z %.4f | ' ...
    'noise delta-z %.4f\n'], test_results.stable_mean_delta_z, ...
    test_results.noise_mean_delta_z);
end
