function test_results = OX_test_searchlight_context_split_half_similarity()
%OX_TEST_SEARCHLIGHT_CONTEXT_SPLIT_HALF_SIMILARITY Focused sanity checks.

previous_rng = rng;
cleanup = onCleanup(@() rng(previous_rng));
rng(314159, 'twister');

%% Physical sphere and minimum-neighborhood behavior
mask = true(7, 7, 7);
affine = diag([2, 2, 2, 1]);
spheres = OX_build_masked_searchlights(mask, affine, 4, 1);
center_linear = sub2ind(size(mask), 4, 4, 4);
center_position = find(spheres.center_linear_indices == center_linear);
assert(isscalar(center_position), 'Synthetic center was not retained.');
assert(spheres.full_sphere_size == 33 && ...
    spheres.neighborhood_sizes(center_position) == 33, ...
    'A 4-mm sphere on a 2-mm grid must contain 33 voxels.');

component_mask = false(9, 9, 9);
isolated_linear = sub2ind(size(component_mask), 2, 2, 2);
component_mask(isolated_linear) = true;
component_mask(5:7, 5:7, 5:7) = true;
restricted = OX_build_masked_searchlights(component_mask, affine, 4, 10);
assert(~ismember(isolated_linear, restricted.center_linear_indices), ...
    'An isolated center incorrectly survived MinVoxels=10.');
assert(all(restricted.neighborhood_sizes >= 10), ...
    'A retained neighborhood violates MinVoxels.');

%% Synthetic split-half data and direct ROI-estimator agreement
n_runs = 8;
n_odors = 4;
n_contexts = 3;
n_features = 40;
trials_per_run = n_odors * n_contexts;
run_ids = repelem((1:n_runs)', trials_per_run);
session_ids = repelem([ones(4, 1); 2 * ones(4, 1)], trials_per_run);
odor_labels = repmat(repelem((1:n_odors)', n_contexts), n_runs, 1);
context_index = repmat(repmat((1:n_contexts)', n_odors, 1), n_runs, 1);
context_order = ["PERSON", "FOOD", "LOCATION"];
context_labels = context_order(context_index)';
context_labels = context_labels(:);
[basis, ~] = qr(randn(n_features, n_contexts), 0);
patterns = (5 * basis)';
patterns = patterns - mean(patterns, 2);
stable_X = patterns(context_index, :) + ...
    0.6 * randn(numel(run_ids), n_features);
noise_X = randn(numel(run_ids), n_features);
neighborhoods = {1:12; 10:25; 20:40};
common_args = {'NumSplits', 10, 'RandomSeed', 17, ...
    'MaxSplitAttempts', 10000, 'ExpectedOdors', n_odors};

stable = OX_searchlight_context_split_half_score(stable_X, ...
    odor_labels, context_labels, run_ids, session_ids, neighborhoods, ...
    common_args{:});
stable_repeat = OX_searchlight_context_split_half_score(stable_X, ...
    odor_labels, context_labels, run_ids, session_ids, neighborhoods, ...
    common_args{:});
noise = OX_searchlight_context_split_half_score(noise_X, ...
    odor_labels, context_labels, run_ids, session_ids, neighborhoods, ...
    common_args{:});
assert(isequaln(stable, stable_repeat), ...
    'Searchlight scoring is not deterministic for a fixed seed.');
assert(all(stable.context_mean_delta_z(:) > 0.5), ...
    'Planted context patterns did not produce positive local effects.');
assert(mean(abs(noise.context_mean_delta_z(:))) < 0.35, ...
    'Synthetic pure-noise effects are unexpectedly large.');
assert(all(stable.cell_trial_counts(:) > 0), ...
    'An accepted split contains an empty context-by-odor cell.');

for center_idx = 1:numel(neighborhoods)
    reference = OX_context_split_half_similarity( ...
        stable_X(:, neighborhoods{center_idx}), odor_labels, ...
        context_labels, run_ids, common_args{:}, ...
        'StratifyGroups', session_ids);
    assert(isequal(reference.split_run_membership, ...
        stable.split_run_membership), ...
        'Searchlight and ROI estimators selected different splits.');
    difference = stable.context_mean_delta_z(center_idx, :) - ...
        reference.aggregate.mean_context_delta_z;
    assert(max(abs(difference)) < 1e-10, ...
        'Searchlight score differs from the direct ROI estimator.');
end

%% Exchangeability and explicit CONTROL exclusion
permuted = OX_permute_semantic_context_within_runs( ...
    context_labels, run_ids, 8080);
for run_idx = 1:n_runs
    in_run = run_ids == run_idx;
    assert(isequal(sort(permuted(in_run)), sort(context_labels(in_run))), ...
        'Within-run permutation changed a run-level context count.');
end
control_rejected = false;
try
    invalid_contexts = context_labels;
    invalid_contexts(1) = "CONTROL";
    OX_searchlight_context_split_half_score(stable_X, odor_labels, ...
        invalid_contexts, run_ids, session_ids, neighborhoods, ...
        common_args{:});
catch
    control_rejected = true;
end
assert(control_rejected, ...
    'The semantic-only scorer did not reject a CONTROL trial.');

incomplete_contexts = context_labels;
incomplete_contexts(odor_labels == 1 & context_labels == "PERSON") = "FOOD";
coverage_error_identifier = "";
try
    OX_searchlight_context_split_half_score(stable_X, odor_labels, ...
        incomplete_contexts, run_ids, session_ids, neighborhoods, ...
        common_args{:});
catch exception
    coverage_error_identifier = string(exception.identifier);
end
assert(coverage_error_identifier == ...
    "OX_DATA:IncompleteContextOdorCoverage", ...
    ['Incomplete context-by-odor coverage must raise the identifier used ' ...
     'by the permutation resampling loop.']);

%% Joint maximum statistic and add-one p-values
n_permutations = 99;
null_stats = randn(4, 3, n_permutations);
observed_stats = zeros(4, 3);
observed_stats(1, 1) = 6;
inference = OX_searchlight_maxstat_inference( ...
    observed_stats, null_stats);
minimum_p = 1 / (n_permutations + 1);
assert(all(inference.p_uncorrected(:) >= minimum_p) && ...
    all(inference.p_fwe(:) >= minimum_p), ...
    'An empirical permutation p-value fell below the add-one minimum.');
assert(all(inference.p_fwe(:) + eps >= inference.p_uncorrected(:)), ...
    'Joint maximum correction produced p_FWE < p_uncorrected.');
assert(inference.p_fwe(1, 1) == minimum_p, ...
    'The planted extreme statistic did not attain the add-one minimum p.');
manual_maximum = nan(n_permutations, 1);
for permutation_idx = 1:n_permutations
    z_map = (null_stats(:, :, permutation_idx) - inference.null_mean) ./ ...
        inference.null_sd;
    manual_maximum(permutation_idx) = max(z_map(:));
end
assert(max(abs(manual_maximum - inference.null_maximum_z)) < 1e-12, ...
    'Stored null maxima do not maximize the complete center-context family.');

test_results = struct( ...
    'sphere_voxels', spheres.full_sphere_size, ...
    'stable_min_delta_z', min(stable.context_mean_delta_z(:)), ...
    'noise_mean_absolute_delta_z', ...
        mean(abs(noise.context_mean_delta_z(:))), ...
    'minimum_empirical_p', minimum_p, ...
    'direct_estimator_match', true, ...
    'exchangeability_pass', true, ...
    'maxstat_pass', true);
fprintf(['Searchlight context-similarity tests passed | sphere %d voxels | ' ...
    'stable min delta-z %.3f | noise mean |delta-z| %.3f\n'], ...
    test_results.sphere_voxels, test_results.stable_min_delta_z, ...
    test_results.noise_mean_absolute_delta_z);
end
