%% Cross-half semantic-context pattern similarity
% Repeatedly split acquisition runs into session-balanced 40/40 halves,
% require all 20 odors in PERSON, FOOD, and LOCATION in both halves, and
% compare same-context with different-context Pearson pattern similarity.
% Repeated splits are used descriptively; they are not independent samples
% for a t-test.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root, 'environment'));
setup_ox;

subject_ids = 2:6;
mri_root = fullfile(project_root, 'MRI');
roi_selection = 'primary';
roi_names = ["PirF", "PirT", "AON", "olfOFC", "olfAMG"];
num_splits = 200;
random_seed = 1;
num_permutations = 5000;
permutation_seed = 1001;
output_dir = fullfile(mri_root, 'group', ...
    'context_split_half_similarity_physio');

OX_test_context_split_half_similarity();

for subject_id = subject_ids
    OX_roi_context_split_half_similarity(subject_id, ...
        'MRIRoot', mri_root, ...
        'ROISelection', roi_selection, ...
        'ROINames', roi_names, ...
        'NumSplits', num_splits, ...
        'RandomSeed', random_seed, ...
        'NumPermutations', num_permutations, ...
        'PermutationSeed', permutation_seed, ...
        'UseParallel', true, ...
        'StratifyBySession', true, ...
        'MinVoxels', 10, ...
        'OutputDir', output_dir, ...
        'SaveOutputs', true);
end

group_results = OX_group_context_split_half_similarity(subject_ids, ...
    'MRIRoot', mri_root, ...
    'OutputDir', output_dir, ...
    'MakePlots', true, ...
    'SaveOutputs', true);

%% Quick smoke-test alternative
% OX_roi_context_split_half_similarity(2, 'MRIRoot', mri_root, ...
%     'ROISelection', roi_selection, 'ROINames', roi_names(1), ...
%     'NumSplits', 2, 'NumPermutations', 2, 'UseParallel', false, ...
%     'OutputDir', output_dir, 'SaveOutputs', false);
