%% Cross-odor generalization of semantic context decoding
% This full analysis runs 1,000 within-run permutations for subjects 2-6,
% followed by exact group sign-flip inference across bilateral ROIs.

project_root = '/Users/qhyang/Desktop/OX_DATA';
addpath(fullfile(project_root, 'environment'));
setup_ox;

subject_ids = 2:6;
mri_root = fullfile(project_root, 'MRI');
roi_selection = 'old'; % 'primary', 'secondary', 'all', or 'old'

OX_test_cross_odor_context_transfer();

for subject_id = subject_ids
    OX_roi_cross_odor_context_transfer(subject_id, ...
        'MRIRoot', mri_root, ...
        'ROISelection', roi_selection, ...
        'MinVoxels', 10, ...
        'NumPermutations', 1000, ...
        'RandomSeed', 1, ...
        'UseParallel', true, ...
        'SaveOutputs', true);
end

group_results = OX_group_cross_odor_context_transfer(subject_ids, ...
    'MRIRoot', mri_root, ...
    'ROISelection', roi_selection, ...
    'MakePlots', true, ...
    'SaveOutputs', true);

%% Smoke-test alternative
% OX_roi_cross_odor_context_transfer(2, 'MRIRoot', mri_root, ...
%     'ROISelection', roi_selection, ...
%     'MaxROIs', 2, 'NumPermutations', 2, ...
%     'UseParallel', false, 'SaveOutputs', false);
