%% ROI-selectable context-similarity searchlight
% Participant-level PERSON, FOOD, and LOCATION context split-half maps.
% Production inference jointly corrects all three maps and every valid
% center with 5,000 within-run label permutations.

project_root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(project_root, 'environment'));
setup_ox;

subject_ids = 2:6;
mri_root = fullfile(project_root, 'MRI');
roi = 'global'; % Default olfactory network; use 'global', 'PirF', or mask path(s).

OX_test_searchlight_context_split_half_similarity();

for subject_id = subject_ids
    OX_searchlight_context_split_half_similarity(subject_id, ...
        'MRIRoot', mri_root, ...
        'ROI', roi, ...
        'SearchlightRadiusMM', 6, ...
        'MinVoxels', 10, ...
        'NumSplits', 200, ...
        'RandomSeed', 1, ...
        'NumPermutations', 5000, ...
        'PermutationSeed', 1001, ...
        'PermutationBatchSize', 25, ...
        'UseParallel', true, ...
        'Resume', true, ...
        'KeepCheckpoint', true, ...
        'SaveOutputs', true);
end

%% Participant smoke-test example (not for inference)
% OX_searchlight_context_split_half_similarity(2, ...
%     'MRIRoot', mri_root, 'NumSplits', 2, 'NumPermutations', 2, ...
%     'UseParallel', false, 'SaveOutputs', false);
