%% Run ROI-based decoding for one subject.
% ROISelection: 'old' preserves the legacy masks; 'primary', 'secondary',
% or 'all' selects the reorganized bilateral sets.

%% Set up
% subjidx = 3;
% target = 'context'; % 'context' or 'odor'
roi_selection = 'primary'; % 'primary', 'secondary', 'all', or 'old'

%% Nearest-template classification

for subjidx = 2:6
    target = 'context'; % 'context' or 'odor'
    template_results = OX_roi_decode_core(subjidx, target, ...
        'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
        'ROISelection', roi_selection, ...
        'Decoder', 'template', ...
        'CrossValidation', 'leave-one-run-out', ... % loro, loo, or kfold10
        'NumRuns', 80, ...
        'R2Threshold', 1, ...
        'RestrictFeaturesToR2', false, ...
        'ScaleVoxels', false, ...
        'DemeanPatterns', true, ...
        'MinVoxels', 10, ...
        'UseParallel', true, ...
        'NumPermutations', 1000, ...
        'RandomSeed', 1);
end


%% Template-evidence score
% score_results = OX_roi_decode_core(subjidx, target, ...
%     'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
%     'ROISelection', roi_selection, ...
%     'Decoder', 'score', ...
%     'CrossValidation', 'leave-one-run-out', ...
%     'NumRuns', 80, ...
%     'R2Threshold', 1, ...
%     'RestrictFeaturesToR2', false, ...
%     'ScaleVoxels', false, ...
%     'DemeanPatterns', true, ...
%     'MinVoxels', 10, ...
%     'UseParallel', true, ...
%     'NumPermutations', 1000, ...
%     'RandomSeed', 1);

%% Linear one-vs-one ECOC SVM
% svm_results = OX_roi_decode_core(subjidx, target, ...
%     'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
%     'ROISelection', roi_selection, ...
%     'Decoder', 'svm', ...
%     'CrossValidation', '10-fold', ...
%     'NumRuns', 80, ...
%     'R2Threshold', 1, ...
%     'RestrictFeaturesToR2', false, ...
%     'ScaleVoxels', false, ...
%     'DemeanPatterns', true, ...
%     'MinVoxels', 10, ...
%     'SVMBoxConstraint', 1, ...
%     'UseParallel', true, ...
%     'NumPermutations', 1000, ...
%     'RandomSeed', 1);

%% Smoke-test settings
% Add 'MaxROIs', 2, 'NumPermutations', 2, 'UseParallel', false to any call.
