%% Run ROI-based decoding for one subject.
% All *_func_thr02 masks in coreg/roi_decoding are included.

%% Set up
subjidx = 2;
target = 'context'; % 'context' or 'odor'

%% Nearest-template classification
template_results = OX_roi_decode_core(subjidx, target, ...
    'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
    'Decoder', 'template', ...
    'CrossValidation', 'leave-one-run-out', ... % loro, loo, or kfold10
    'NumRuns', 80, ...
    'R2Threshold', 1, ...
    'RestrictFeaturesToR2', false, ...
    'ScaleVoxels', false, ...
    'DemeanPatterns', true, ...
    'MinVoxels', 10, ...
    'UseParallel', true, ...
    'NumPermutations', 1000, ...
    'RandomSeed', 1);

%% Template-evidence score
% score_results = OX_roi_decode_core(subjidx, target, ...
%     'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
%     'Decoder', 'score', ...
%     'CrossValidation', 'leave-one-run-out', ...
%     'NumRuns', 80, ...
%     'R2Threshold', 1, ...
%     'RestrictFeaturesToR2', false, ...
%     'ScaleVoxels', false, ...
%     'DemeanPatterns', true, ...
%     'MinVoxels', 10, ...
%     'UseParallel', true, ...
%     'NumPermutations', 1000, ...
%     'RandomSeed', 1);

%% Linear one-vs-one ECOC SVM
% svm_results = OX_roi_decode_core(subjidx, target, ...
%     'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
%     'Decoder', 'svm', ...
%     'CrossValidation', '10-fold', ...
%     'NumRuns', 80, ...
%     'R2Threshold', 1, ...
%     'RestrictFeaturesToR2', false, ...
%     'ScaleVoxels', false, ...
%     'DemeanPatterns', true, ...
%     'MinVoxels', 10, ...
%     'SVMBoxConstraint', 1, ...
%     'UseParallel', true, ...
%     'NumPermutations', 1000, ...
%     'RandomSeed', 1);

%% Smoke-test settings
% Add 'MaxROIs', 2, 'NumPermutations', 2, 'UseParallel', false to any call.
