%% run context and odor decoding for each subject 

%% set up 
subjidx = 2; 
%% 

context_results = OX_searchlight_context(subjidx, ...
    'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
    'NumRuns', 80, ...
    'R2Threshold', 1, ...
    'RestrictFeaturesToR2', false, ...
    'ScaleVoxels', false, ...
    'SearchlightRadius', 3, ...
    'MinVoxels', 10, ...
    'UseParallel', true, ...
    'NumPermutations', 1000, ...
    'CrossValidation', 'leave-one-out');

% %% 
% odor_results = OX_searchlight_odor(subjidx, ...
%     'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
%     'NumRuns', 80, ...
%     'R2Threshold', 1, ...
%     'RestrictFeaturesToR2', false, ...
%     'ScaleVoxels', false, ...
%     'SearchlightRadius', 3, ...
%     'MinVoxels', 10, ...
%     'UseParallel', true, ...
%     'NumPermutations', 1000, ...
%     'CrossValidation', 'leave-one-out');

%% template matching odor decoding doesn't work. Try a similarity score instead. 
odor_results = OX_searchlight_score_core(subjidx, 'odor', ...
    'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
    'NumRuns', 80, ...
    'R2Threshold', 1, ...
    'RestrictFeaturesToR2', false, ...
    'ScaleVoxels', false, ...
    'SearchlightRadius', 3, ...
    'MinVoxels', 10, ...
    'UseParallel', true, ...
    'NumPermutations', 1000, ...
    'CrossValidation', 'leave-one-out');

%% try score decoding on context 
context_results = OX_searchlight_score_core(subjidx, 'context', ...
    'MRIRoot', '/Users/qhyang/Desktop/OX_DATA/MRI', ...
    'NumRuns', 80, ...
    'R2Threshold', 1, ...
    'RestrictFeaturesToR2', false, ...
    'ScaleVoxels', false, ...
    'SearchlightRadius', 3, ...
    'MinVoxels', 10, ...
    'UseParallel', true, ...
    'NumPermutations', 1000, ...
    'CrossValidation', 'leave-one-out');